export * from './HomePage'
export * from './LoginPage'
export * from './ServicesPage'
export * from './Form'
export * from './Gallery'
export * from './Grid'
export * from './NavBar'
export * from './Task'